/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var checkType      = kurentoClient.checkType;
var ChecktypeError = checkType.ChecktypeError;


var Transaction = kurentoClient.TransactionsManager.Transaction;

var Hub = kurentoClient.register.abstracts.Hub;


function noop(error, result) {
  if (error) console.trace(error);

  return result
};


/**
 * Create an element
 *
 * @classdesc
 *  mnscmixer interface. Documentation about the module
 *
 * @extends module:core/abstracts.Hub
 *
 * @constructor module:mnscmixer.mnscmixer
 */
function mnscmixer(){
  mnscmixer.super_.call(this);
};
inherits(mnscmixer, Hub);


//
// Public methods
//

/**
 * .
 *
 * @alias module:mnscmixer.mnscmixer.focus
 *
 * @param {external:Integer} sink_id
 *  Source port to be connected
 *
 * @param {external:Integer} param
 *  Source port to be connected
 *
 * @param {module:mnscmixer.mnscmixer~focusCallback} [callback]
 *
 * @return {external:Promise}
 */
mnscmixer.prototype.focus = function(sink_id, param, callback){
  var transaction = (arguments[0] instanceof Transaction)
                  ? Array.prototype.shift.apply(arguments)
                  : undefined;

  //  
  // checkType('int', 'sink_id', sink_id, {required: true});
  //  
  // checkType('int', 'param', param, {required: true});
  //  

  var params = {
    sink_id: sink_id,
    param: param
  };

  callback = (callback || noop).bind(this)

  return disguise(this._invoke(transaction, 'focus', params, callback), this)
};
/**
 * @callback module:mnscmixer.mnscmixer~focusCallback
 * @param {external:Error} error
 */


/**
 * @alias module:mnscmixer.mnscmixer.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the parent {@link module:core.MediaPipeline MediaPipeline}
 */
mnscmixer.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:mnscmixer.mnscmixer.events
 *
 * @extends module:core/abstracts.Hub.events
 */
mnscmixer.events = Hub.events;


/**
 * Checker for {@link module:mnscmixer.mnscmixer}
 *
 * @memberof module:mnscmixer
 *
 * @param {external:String} key
 * @param {module:mnscmixer.mnscmixer} value
 */
function checkmnscmixer(key, value)
{
  if(!(value instanceof mnscmixer))
    throw ChecktypeError(key, mnscmixer, value);
};


module.exports = mnscmixer;

mnscmixer.check = checkmnscmixer;
